In [45]:
pip install pm4py

Requirement already satisfied: pm4py in c:\users\user\anaconda3\lib\site-packages (2.2.28)
Requirement already satisfied: numpy>=1.19.5 in c:\users\user\anaconda3\lib\site-packages (from pm4py) (1.20.1)
Requirement already satisfied: sympy in c:\users\user\anaconda3\lib\site-packages (from pm4py) (1.8)
Requirement already satisfied: tqdm in c:\users\user\anaconda3\lib\site-packages (from pm4py) (4.59.0)
Requirement already satisfied: pandas>=1.1.5 in c:\users\user\anaconda3\lib\site-packages (from pm4py) (1.2.4)
Requirement already satisfied: intervaltree in c:\users\user\anaconda3\lib\site-packages (from pm4py) (3.1.0)
Requirement already satisfied: pyvis in c:\users\user\anaconda3\lib\site-packages (from pm4py) (0.2.1)
Requirement already satisfied: deprecation in c:\users\user\anaconda3\lib\site-packages (from pm4py) (2.1.0)
Requirement already satisfied: graphviz in c:\users\user\anaconda3\lib\site-packages (from pm4py) (0.19.1)
Requirement already satisfied: jsonpickle in c:\users\user\anaconda3\lib\site-packages (from pm4py) (2.2.0)
Requirement already satisfied: pytz in c:\users\user\anaconda3\lib\site-packages (from pm4py) (2021.1)
Requirement already satisfied: networkx in c:\users\user\anaconda3\lib\site-packages (from pm4py) (2.5)
Requirement already satisfied: lxml in c:\users\user\anaconda3\lib\site-packages (from pm4py) (4.6.3)
Requirement already satisfied: scipy in c:\users\user\anaconda3\lib\site-packages (from pm4py) (1.6.2)
Requirement already satisfied: stringdist in c:\users\user\anaconda3\lib\site-packages (from pm4py) (1.0.9)
Requirement already satisfied: pydotplus in c:\users\user\anaconda3\lib\site-packages (from pm4py) (2.0.2)
Requirement already satisfied: cvxopt in c:\users\user\anaconda3\lib\site-packages (from pm4py) (1.3.0)
Requirement already satisfied: matplotlib in c:\users\user\anaconda3\lib\site-packages (from pm4py) (3.3.4)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\user\anaconda3\lib\site-packages (from pandas>=1.1.5->pm4py) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=1.1.5->pm4py) (1.15.0)
Requirement already satisfied: packaging in c:\users\user\anaconda3\lib\site-packages (from deprecation->pm4py) (20.9)
Requirement already satisfied: sortedcontainers<3.0,>=2.0 in c:\users\user\anaconda3\lib\site-packages (from intervaltree->pm4py) (2.3.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->pm4py) (8.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->pm4py) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->pm4py) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->pm4py) (1.3.1)
Requirement already satisfied: decorator>=4.3.0 in c:\users\user\anaconda3\lib\site-packages (from networkx->pm4py) (5.0.6)
Requirement already satisfied: ipython>=5.3.0 in c:\users\user\anaconda3\lib\site-packages (from pyvis->pm4py) (7.22.0)
Requirement already satisfied: jinja2>=2.9.6 in c:\users\user\anaconda3\lib\site-packages (from pyvis->pm4py) (2.11.3)
Requirement already satisfied: setuptools>=18.5 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis->pm4py) (52.0.0.post20210125)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis->pm4py) (3.0.17)
Requirement already satisfied: backcall in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis->pm4py) (0.2.0)
Requirement already satisfied: jedi>=0.16 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis->pm4py) (0.17.2)
Requirement already satisfied: pygments in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis->pm4py) (2.8.1)
Requirement already satisfied: pickleshare in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis->pm4py) (0.7.5)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis->pm4py) (0.4.4)
Requirement already satisfied: traitlets>=4.2 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis->pm4py) (5.0.5)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\users\user\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=5.3.0->pyvis->pm4py) (0.7.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\user\anaconda3\lib\site-packages (from jinja2>=2.9.6->pyvis->pm4py) (1.1.1)
Requirement already satisfied: wcwidth in c:\users\user\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->pyvis->pm4py) (0.2.5)
Requirement already satisfied: ipython-genutils in c:\users\user\anaconda3\lib\site-packages (from traitlets>=4.2->ipython>=5.3.0->pyvis->pm4py) (0.2.0)
Requirement already satisfied: mpmath>=0.19 in c:\users\user\anaconda3\lib\site-packages (from sympy->pm4py) (1.2.1)
Note: you may need to restart the kernel to use updated packages.

In [46]:
import pandas as pd
import numpy as np
import pm4py

In [47]:
df = pd.read_csv('https://github.com/hilaler/predict-the-processing-time-of-video-digital-conversion-process/blob/main/problem_2.csv?raw=true', sep=',')
df = pm4py.format_dataframe(df, case_id='Case ID', activity_key='Activity', timestamp_key='Start Timestamp')
log = pm4py.convert_to_event_log(df)

In [48]:
df['Start Timestamp'] = pd.to_datetime(df['Start Timestamp'])
df['Complete Timestamp'] = pd.to_datetime(df['Complete Timestamp'])
df['total time'] = df['Complete Timestamp'] - df['Start Timestamp']
df.head()

,Case ID,Start Timestamp,Complete Timestamp,Activity,Resource,Role,case:concept:name,concept:name,time:timestamp,@@index,total time
0,1,2011-01-01 00:00:00+00:00,2011-01-01 00:37:00+00:00,Create Purchase Requisition,Kim Passa,Requester,1,Create Purchase Requisition,2011-01-01 00:00:00+00:00,0,0 days 00:37:00
1,1,2011-01-01 05:37:00+00:00,2011-01-01 05:45:00+00:00,Create Request for Quotation Requester,Kim Passa,Requester,1,Create Request for Quotation Requester,2011-01-01 05:37:00+00:00,1,0 days 00:08:00
2,1,2011-01-01 06:41:00+00:00,2011-01-01 06:55:00+00:00,Analyze Request for Quotation,Karel de Groot,Purchasing Agent,1,Analyze Request for Quotation,2011-01-01 06:41:00+00:00,2,0 days 00:14:00
3,1,2011-01-01 11:43:00+00:00,2011-01-01 12:09:00+00:00,Send Request for Quotation to Supplier,Karel de Groot,Purchasing Agent,1,Send Request for Quotation to Supplier,2011-01-01 11:43:00+00:00,3,0 days 00:26:00
4,1,2011-01-01 12:32:00+00:00,2011-01-01 16:03:00+00:00,Create Quotation comparison Map,Magdalena Predutta,Purchasing Agent,1,Create Quotation comparison Map,2011-01-01 12:32:00+00:00,4,0 days 03:31:00

In [49]:
df = df.drop(columns=["Role"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9119 entries, 0 to 9118
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Case ID             9119 non-null   int64
 1   Start Timestamp     9119 non-null   datetime64[ns, UTC]
 2   Complete Timestamp  9119 non-null   datetime64[ns, UTC]
 3   Activity            9119 non-null   object
 4   Resource            9119 non-null   object
 5   case:concept:name   9119 non-null   string
 6   concept:name        9119 non-null   string
 7   time:timestamp      9119 non-null   datetime64[ns, UTC]
 8   @@index             9119 non-null   int64
 9   total time          9119 non-null   timedelta64[ns]
dtypes: datetime64[ns, UTC](3), int64(2), object(2), string(2), timedelta64[ns](1)
memory usage: 712.5+ KB

In [57]:
start_activities = pm4py.get_start_activities(df)
start_activities

{'Create Purchase Requisition': 608}

In [51]:
end_activities = pm4py.get_end_activities(df)
end_activities

{'Pay invoice': 413,
 'Analyze Request for Quotation': 131,
 'Analyze Purchase Requisition': 64}

In [52]:
filtered_log = pm4py.filter_end_activities(df, ["Pay invoice"])
filtered_log

,Case ID,Start Timestamp,Complete Timestamp,Activity,Resource,case:concept:name,concept:name,time:timestamp,@@index,total time
0,1,2011-01-01 00:00:00+00:00,2011-01-01 00:37:00+00:00,Create Purchase Requisition,Kim Passa,1,Create Purchase Requisition,2011-01-01 00:00:00+00:00,0,0 days 00:37:00
1,1,2011-01-01 05:37:00+00:00,2011-01-01 05:45:00+00:00,Create Request for Quotation Requester,Kim Passa,1,Create Request for Quotation Requester,2011-01-01 05:37:00+00:00,1,0 days 00:08:00
2,1,2011-01-01 06:41:00+00:00,2011-01-01 06:55:00+00:00,Analyze Request for Quotation,Karel de Groot,1,Analyze Request for Quotation,2011-01-01 06:41:00+00:00,2,0 days 00:14:00
3,1,2011-01-01 11:43:00+00:00,2011-01-01 12:09:00+00:00,Send Request for Quotation to Supplier,Karel de Groot,1,Send Request for Quotation to Supplier,2011-01-01 11:43:00+00:00,3,0 days 00:26:00
4,1,2011-01-01 12:32:00+00:00,2011-01-01 16:03:00+00:00,Create Quotation comparison Map,Magdalena Predutta,1,Create Quotation comparison Map,2011-01-01 12:32:00+00:00,4,0 days 03:31:00
...,...,...,...,...,...,...,...,...,...,...
9108,99,2011-01-21 10:57:00+00:00,2011-01-21 10:58:00+00:00,Approve Purchase Order for payment,Francois de Perrier,99,Approve Purchase Order for payment,2011-01-21 10:57:00+00:00,9108,0 days 00:01:00
9109,99,2011-01-22 07:30:00+00:00,2011-01-22 07:30:00+00:00,Send invoice,Kiu Kan,99,Send invoice,2011-01-22 07:30:00+00:00,9109,0 days 00:00:00
9110,99,2011-01-22 21:51:00+00:00,2011-01-22 21:56:00+00:00,Release Supplier's Invoice,Karalda Nimwada,99,Release Supplier's Invoice,2011-01-22 21:51:00+00:00,9110,0 days 00:05:00
9111,99,2011-01-22 21:56:00+00:00,2011-01-22 21:56:00+00:00,Authorize Supplier's Invoice payment,Karalda Nimwada,99,Authorize Supplier's Invoice payment,2011-01-22 21:56:00+00:00,9111,0 days 00:00:00
9112,99,2011-01-22 22:43:00+00:00,2011-01-22 22:51:00+00:00,Pay invoice,Pedro Alvares,99,Pay invoice,2011-01-22 22:43:00+00:00,9112,0 days 00:08:00

In [53]:
tracefilter_df_pos = pm4py.filter_event_attribute_values(df, "Resource", ["Pedro Alvares"], level="event", retain=True)
tracefilter_df_pos

,Case ID,Start Timestamp,Complete Timestamp,Activity,Resource,case:concept:name,concept:name,time:timestamp,@@index,total time
16,1,2011-01-04 15:22:00+00:00,2011-01-04 15:31:00+00:00,Pay invoice,Pedro Alvares,1,Pay invoice,2011-01-04 15:22:00+00:00,16,0 days 00:09:00
34,10,2011-01-10 16:03:00+00:00,2011-01-10 16:16:00+00:00,Pay invoice,Pedro Alvares,10,Pay invoice,2011-01-10 16:03:00+00:00,34,0 days 00:13:00
67,1009,2011-08-30 19:46:00+00:00,2011-08-30 19:52:00+00:00,Release Supplier's Invoice,Pedro Alvares,1009,Release Supplier's Invoice,2011-08-30 19:46:00+00:00,67,0 days 00:06:00
69,1009,2011-08-30 20:09:00+00:00,2011-08-30 20:23:00+00:00,Pay invoice,Pedro Alvares,1009,Pay invoice,2011-08-30 20:09:00+00:00,69,0 days 00:14:00
85,101,2011-01-28 21:33:00+00:00,2011-01-28 21:39:00+00:00,Release Supplier's Invoice,Pedro Alvares,101,Release Supplier's Invoice,2011-01-28 21:33:00+00:00,85,0 days 00:06:00
...,...,...,...,...,...,...,...,...,...,...
9044,976,2011-08-23 17:46:00+00:00,2011-08-23 17:48:00+00:00,Release Supplier's Invoice,Pedro Alvares,976,Release Supplier's Invoice,2011-08-23 17:46:00+00:00,9044,0 days 00:02:00
9045,976,2011-08-23 17:48:00+00:00,2011-08-23 17:48:00+00:00,Authorize Supplier's Invoice payment,Pedro Alvares,976,Authorize Supplier's Invoice payment,2011-08-23 17:48:00+00:00,9045,0 days 00:00:00
9088,981,2011-06-08 02:21:00+00:00,2011-06-08 02:21:00+00:00,Authorize Supplier's Invoice payment,Pedro Alvares,981,Authorize Supplier's Invoice payment,2011-06-08 02:21:00+00:00,9088,0 days 00:00:00
9089,981,2011-06-08 03:10:00+00:00,2011-06-08 03:20:00+00:00,Pay invoice,Pedro Alvares,981,Pay invoice,2011-06-08 03:10:00+00:00,9089,0 days 00:10:00
9112,99,2011-01-22 22:43:00+00:00,2011-01-22 22:51:00+00:00,Pay invoice,Pedro Alvares,99,Pay invoice,2011-01-22 22:43:00+00:00,9112,0 days 00:08:00

In [54]:
print("Cases that involved Pedro Alvares as the Resources is: ", len(tracefilter_df_pos.value_counts('Case ID')))

Cases that involved Pedro Alvares as the Resources is:  360

In [55]:
tracefilter_settle = pm4py.filter_event_attribute_values(df, "Activity", ["Settle dispute with supplier Purchasing Agent"], level="event", retain=True)
tracefilter_settle.head()

,Case ID,Start Timestamp,Complete Timestamp,Activity,Resource,case:concept:name,concept:name,time:timestamp,@@index,total time
920,1178,2011-09-26 01:02:00+00:00,2011-09-26 10:23:00+00:00,Settle dispute with supplier Purchasing Agent,Magdalena Predutta,1178,Settle dispute with supplier Purchasing Agent,2011-09-26 01:02:00+00:00,920,0 days 09:21:00
1299,124,2011-01-29 08:32:00+00:00,2011-01-29 17:39:00+00:00,Settle dispute with supplier Purchasing Agent,Karel de Groot,124,Settle dispute with supplier Purchasing Agent,2011-01-29 08:32:00+00:00,1299,0 days 09:07:00
1505,13,2011-01-07 21:34:00+00:00,2011-01-08 06:37:00+00:00,Settle dispute with supplier Purchasing Agent,Francois de Perrier,13,Settle dispute with supplier Purchasing Agent,2011-01-07 21:34:00+00:00,1505,0 days 09:03:00
1840,1375,2011-09-18 15:07:00+00:00,2011-09-19 00:10:00+00:00,Settle dispute with supplier Purchasing Agent,Francois de Perrier,1375,Settle dispute with supplier Purchasing Agent,2011-09-18 15:07:00+00:00,1840,0 days 09:03:00
1893,1388,2011-09-25 16:15:00+00:00,2011-09-26 01:12:00+00:00,Settle dispute with supplier Purchasing Agent,Francois de Perrier,1388,Settle dispute with supplier Purchasing Agent,2011-09-25 16:15:00+00:00,1893,0 days 08:57:00

In [56]:
print("Cases that involved Settle dispute with supplier Purchasing Agent Activity: ", len(tracefilter_settle.value_counts("Case ID")))

Cases that involved Settle dispute with supplier Purchasing Agent Activity:  24